### PR TITLE
V2.5.0

### PR DESCRIPTION
**Pull request by cofinoa**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by cofinoa** [comment]
@conda-forge-admin, please rerender

**Comment by dbast** [comment]
requires https://github.com/conda-forge/r-tfautograph-feedstock/pull/2 being available

**Comment by cofinoa** [comment]
@conda-forge-admin, please restart ci

**Comment by cofinoa** [comment]
The CI still build from v2.9.0. 

I had created the v2.5.0 branch from v2.5.0 commit, and this can cause some confusion. 

I'm closing and creating a new branch from the HEAD.

**Pull request closed without merging**
